### ISSUE TITLE
Release Stable Version for Tauri@2

### ISSUE THREAD

**Issue by WhyFenceCode** [meslzy/tauri-plugin-wallpaper#1]
Is this version 1 or v2? and if not v2 can we get an option for v2?

**Comment by meslzy** [comment]
Hey, when they finally released the new version ( stable not beta ) I'll make sure the library compatible with the version released.

**Comment by WhyFenceCode** [comment]
hey @meslzy not sure if you remember this, what are your thoughts on making a v2 version now that its out?

**Comment by meslzy** [comment]
Hey @WhyFenceCode, I'll release V2 soon.

**Comment by wangrongding** [comment]
Is there a way to be compatible with macOS?

**Comment by WhyFenceCode** [comment]
sorry to bug you on this, I am waiting for this for a project of mine

**Comment by meslzy** [comment]
> Is there a way to be compatible with macOS?

For now i didn't implement any functionality for MacOS or Linux.
But in the future may the feature implemented.

**Comment by meslzy** [comment]
I have published beta version.
[https://crates.io/crates/tauri-plugin-wallpaper/2.0.0-beta](https://crates.io/crates/tauri-plugin-wallpaper/2.0.0-beta)
use `npm run tauri add wallpaper`
