### ISSUE TITLE
Plugin not found error for the npm version

### ISSUE THREAD

**Issue by WhyFenceCode** [meslzy/tauri-plugin-wallpaper#3]
This is probably on me and not the plugin, but I wanted to verify. I am using the npm version with PNPM. I have a very simple file whose sole job is to make this function as a wallpaper. There are no errors when write it, and I have it installed, but when I run the code I get `Uncaught (in promise) wallpaper.attach not allowed. Plugin not found`

My code for the file is as follows:
```js
import { register } from '@tauri-apps/plugin-global-shortcut';
import wallpaper from "tauri-plugin-wallpaper";
import { getCurrentWindow } from '@tauri-apps/api/window';

let isWallpaper = true;

await getCurrentWindow().setFullscreen(true);

wallpaper.attach();

await register('CommandOrControl+Alt+W', () => {
    if (isWallpaper) {
        wallpaper.detach();
    } else {
        wallpaper.attach();
    }
});
```
Full Repo
https://github.com/WhyFenceCode/WallPaperTauriApp

**Comment by meslzy** [comment]
Okay so you did not add the plugin to Rust. 
I'll update the readme and ill guide you through it.

**Comment by meslzy** [comment]
First you need to install the tauri plugin, cd to your `src-tauri` and run

```bash
cargo add tauri-plugin-wallpaper@2
```

Then add the plugin permissions, cd to `src-tauri\capabilities\default.json`

```json
{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": ["main"],
  "permissions": [
    "core:default",
    "opener:default",
    "wallpaper:default", // add this
    "core:window:allow-set-fullscreen"
  ]
}
```
Now go to your entry file `src-tauri\src\lib.rs` and add the plugin

```rust
// Learn more about Tauri commands at https://tauri.app/develop/calling-rust/
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_global_shortcut::Builder::new().build())
        .plugin(tauri_plugin_wallpaper::init()) // add this line
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

```

Plz if this works, close the issue and thanks for using the plugin 💗

**Comment by WhyFenceCode** [comment]
Makes sense, so I need both, I was a little lost so thank you for the clarification

**Comment by WhyFenceCode** [comment]
@meslzy I followed all the steps you gave (I even uninstalled the beta 2.0.0 pnpm to install the non-beta version, but I now get an error that states `Uncaught (in promise) WorkerW window not found` which is very confusing to me

My JS is here:
```js
import { register } from '@tauri-apps/plugin-global-shortcut';
import wallpaper from "tauri-plugin-wallpaper";
import { getCurrentWindow } from '@tauri-apps/api/window';

let isWallpaper = true;

await getCurrentWindow().setFullscreen(true);
canStart = true;

wallpaper.attach();

await register('CommandOrControl+Alt+W', () => {
    if (isWallpaper) {
        wallpaper.detach();
    } else {
        wallpaper.attach();
    }
});
```

and the Rust is here:
```rs
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_global_shortcut::Builder::new().build())
        .plugin(tauri_plugin_wallpaper::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

Please don't take any offence to this but I think the documentation needs to be better. I can rewrite it when I have time and once I understand how this works if you would like.

**Comment by meslzy** [comment]
Yes, this another issue currently investigating in.

See #2 .

But at this point you already solved your issue.

The issue you're currently encountering involves the plugin attempting to spawn the WorkerW layer, which we use to position any application on top, allowing the window to appear behind desktop icons.

This happens a lot to my plugin users. And never happened to me (some-how) .


Please send your system version.

**Comment by WhyFenceCode** [comment]
What do you mean by system version? i am on windows 11 64 bit, idk what else to tell you, pls let me know. Also have a great holiday!
